train:
  source:
    ${data_zooms}

  target:
    ${data_zooms}

  timesteps: ["0-29705"]
  variables: ${data_variables}

val:
  source:
    ${data_zooms}

  target:
    ${data_zooms}

  timesteps: [29705,29802,29899,29997,30094,30192,30289,30386,30484,30581,30679,30776,30873,30971]
  variables: ${data_variables}

test:
  source:
    ${data_zooms}

  target:
    ${data_zooms}
    
  timesteps: ["29705-31166"]
  variables: ${data_variables}