defaults:
  - trainer: trainer
  - logger: wandb
  - model: FST_4M
  - mgrids: healpix
  - data_zooms: default
  - data_variables: default
  - data_split: default
  - dataloader: healpix_SR_358
  - embedding: default
  - hydra: default
  - _self_

ckpt_path: null

run_name: FST_4M
config_name: default
project_name: SR_ERA5
run_dir: run/